# Generated by Django 4.2.4 on 2023-11-09 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Москва', max_length=100, verbose_name='Название')),
                ('foundation_date', models.IntegerField(default=1147, verbose_name='Дата основания')),
                ('grp', models.BigIntegerField(default=20450000000000, verbose_name='ВВП')),
                ('climate', models.CharField(default='умеренный', max_length=255, verbose_name='Климат')),
                ('square', models.IntegerField(default=2561, verbose_name='Площадь')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('description', models.CharField(blank=True, default='Москва — столица и крупнейший город России. Сюда ведут многие пути и человеческие судьбы, с этим городом связано множество роковых и знаменательных событий истории, людских радостей и надежд, несчастий и разочарований, разумеется, легенд, мифов и преданий. Москва — блистательный город, во всех отношениях достойный называться столицей. Здесь великолепные памятники архитектуры и живописные парки, самые лучшие магазины и высокие небоскребы, длинное метро и заполненные вокзалы. Москва никогда не спит, здесь трудятся с утра до поздней ночи, а затем веселятся до утра.', max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(default='cities/Москва.jpg', upload_to='cities', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 45, 57, 543822, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 45, 57, 543822, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 45, 57, 543822, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('cities', models.ManyToManyField(null=True, to='bmstu_lab.city', verbose_name='Города')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
