# Generated by Django 4.2.4 on 2023-10-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('foundation_date', models.IntegerField(blank=True, null=True)),
                ('grp', models.BigIntegerField(blank=True, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('square', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('url_photo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=120)),
                ('admin', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_vacancy', models.CharField(max_length=255)),
                ('date_create', models.DateField()),
                ('date_publication', models.DateField()),
                ('date_close', models.DateField()),
                ('status_vacancy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyCity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_vacancy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancycity',
                'managed': False,
            },
        ),
    ]
