# Generated by Django 4.2.4 on 2023-11-11 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 13, 41, 21, 314691, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 13, 41, 21, 314691, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 13, 41, 21, 314691, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
