# Generated by Django 4.2.4 on 2023-11-09 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_vacancy_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 46, 33, 925314, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 46, 33, 925314, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 46, 33, 925314, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
